[features]
seeds = false
skip-lint = false
[programs.localnet]
apmsdapp = "GuXZpX5WsfxdBMeeCdzuVpfMjzNKJn1ZvdoZwb5A3d8T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
